# Set some variables for convenience
substitutions:
  node_name: nspanel-guest-bedroom
  device_name: Guest Bedroom Switch
  target_thermostat: climate.guest_bedroom_minisplit

external_components:
  - source: github://pr#2956
    components: [nextion]
    refresh: 1h

esphome:
  name: $node_name
  comment: $device_name

esp32:
  board: esp32dev

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

# Enable logging
logger:
  level: debug

# Enable wireless updates
ota:

# Enable Home Assistant API
api:
  services:
    # Service to play a song
    - service: play_rtttl
      variables:
        song_str: string
      then:
        - rtttl.play:
            rtttl: !lambda 'return song_str;'
    - service: upload_tft
      then:
        - lambda: 'id(disp1)->upload_tft();'
    - service: send_command
      variables:
        cmd: string
      then:
        - lambda: 'id(disp1).send_command_printf("%s", cmd.c_str());'

# A reboot button is always useful
button:
  - platform: restart
    name: Restart $device_name

# Define some inputs
binary_sensor:
  - platform: gpio
    name: $device_name Left Button
    pin:
      number: 14
      inverted: true
    on_click:
      - switch.toggle: relay_1

  - platform: gpio
    name: $device_name Right Button
    pin:
      number: 27
      inverted: true
    on_click:
      - switch.toggle: relay_2
  
  - platform: nextion
    name: $device_name Minus Button
    page_id: 0
    component_id: 1
    on_release:
      then:
        - rtttl.play: "twobits:d=4,o=0,b=6000:a0"
        - homeassistant.service:
            service: climate.set_temperature
            data_template:
              entity_id: $target_thermostat
              temperature: '{{ (state_attr("$target_thermostat", "temperature")|round(0)) - 1 }}'
    
  - platform: nextion
    name: $device_name Plus Button
    page_id: 0
    component_id: 2
    on_release:
      then:
        - rtttl.play: "twobits:d=4,o=0,b=6000:a0"
        - homeassistant.service:
            service: climate.set_temperature
            data_template:
              entity_id: $target_thermostat
              temperature: '{{ (state_attr("$target_thermostat", "temperature")|round(0)) + 1 }}'
    
  - platform: nextion
    name: $device_name Heat Button
    page_id: 0
    component_id: 6
    on_release:
      then:
        - if:
            condition:
              lambda: 'return id(current_mode).state == "heatActive";'
            then:
              - rtttl.play: "twobits:d=4,o=0,b=6000:a0"
              - homeassistant.service:
                  service: climate.set_hvac_mode
                  data:
                    entity_id: $target_thermostat
                    hvac_mode: 'off'
            else:
              - rtttl.play: "twobits:d=4,o=0,b=6000:a0"
              - homeassistant.service:
                  service: climate.set_hvac_mode
                  data:
                    entity_id: $target_thermostat
                    hvac_mode: heat
    
  - platform: nextion
    name: $device_name Cool Button
    page_id: 0
    component_id: 7
    on_release:
      then:
        - if:
            condition:
              lambda: 'return id(current_mode).state == "coolActive";'
            then:
              - rtttl.play: "twobits:d=4,o=0,b=6000:a0"
              - homeassistant.service:
                  service: climate.set_hvac_mode
                  data:
                    entity_id: $target_thermostat
                    hvac_mode: 'off'
            else:
              - rtttl.play: "twobits:d=4,o=0,b=6000:a0"
              - homeassistant.service:
                  service: climate.set_hvac_mode
                  data:
                    entity_id: $target_thermostat
                    hvac_mode: cool
    
  - platform: nextion
    name: $device_name Humidity Button
    page_id: 0
    component_id: 8
    on_release:
      then:
        - if:
            condition:
              lambda: 'return id(current_mode).state == "dryActive";'
            then:
              - rtttl.play: "twobits:d=4,o=0,b=6000:a0"
              - homeassistant.service:
                  service: climate.set_hvac_mode
                  data:
                    entity_id: $target_thermostat
                    hvac_mode: 'off'
            else:
              - rtttl.play: "twobits:d=4,o=0,b=6000:a0"
              - homeassistant.service:
                  service: climate.set_hvac_mode
                  data:
                    entity_id: $target_thermostat
                    hvac_mode: dry
    
  - platform: nextion
    name: $device_name Fan Button
    page_id: 0
    component_id: 9
    on_release:
        - if:
            condition:
              lambda: 'return id(current_mode).state == "fanActive";'
            then:
              - rtttl.play: "twobits:d=4,o=0,b=6000:a0"
              - homeassistant.service:
                  service: climate.set_hvac_mode
                  data:
                    entity_id: $target_thermostat
                    hvac_mode: 'off'
            else:
              - rtttl.play: "twobits:d=4,o=0,b=6000:a0"
              - homeassistant.service:
                  service: climate.set_hvac_mode
                  data:
                    entity_id: $target_thermostat
                    hvac_mode: fan_only
    
  - platform: nextion
    name: $device_name Vertical Vane Button
    page_id: 0
    component_id: 10
    
  - platform: nextion
    name: $device_name Horizontal Vane Button
    page_id: 0
    component_id: 11

sensor:
  - platform: wifi_signal
    name: $device_name WiFi Signal
    update_interval: 60s

  - platform: ntc
    id: temperature
    sensor: resistance_sensor
    calibration:
      b_constant: 3950
      reference_temperature: 25°C
      reference_resistance: 10kOhm
    name: $device_name Temperature

  - platform: resistance
    id: resistance_sensor
    sensor: ntc_source
    configuration: DOWNSTREAM
    resistor: 11.2kOhm

  - platform: adc
    id: ntc_source
    pin: 38
    update_interval: 10s
    attenuation: 11db
    
  - platform: homeassistant
    id: target_temperature
    entity_id: $target_thermostat
    attribute: temperature
    on_value:
      then:
        - if:
            condition:
              lambda: 'return id(current_mode).state == "0";'
            then:
              - lambda: 'id(disp1).set_component_text_printf("targetTemp", "--""\xb0");'
            else:
              - lambda: 'id(disp1).set_component_text_printf("targetTemp", "%i""\xb0", (int)x);'
        
  - platform: homeassistant
    id: current_temperature
    entity_id: $target_thermostat
    attribute: current_temperature
    on_value:
      then:
        - lambda: 'id(disp1).set_component_text_printf("currentTemp", "%i""\xb0", (int)x);'

text_sensor:
  - platform: homeassistant
    id: current_mode
    entity_id: $target_thermostat
    filters:
      - map:
        - off -> 0
        - heat -> heatActive
        - cool -> coolActive
        - dry -> dryActive
        - fan_only -> fanActive
        - heat_cool -> 0
    on_value:
      then:
        - if:
            condition:
              lambda: 'return x == "0";'
            then:
              - lambda: 'id(disp1).send_command_printf("vis heatActive,0");'
              - lambda: 'id(disp1).send_command_printf("vis coolActive,0");'
              - lambda: 'id(disp1).send_command_printf("vis dryActive,0");'
              - lambda: 'id(disp1).send_command_printf("vis fanActive,0");'
              - lambda: 'id(disp1).set_component_text_printf("targetTemp", "--""\xb0");'
            else:
              - lambda: 'id(disp1).send_command_printf("vis heatActive,0");'
              - lambda: 'id(disp1).send_command_printf("vis coolActive,0");'
              - lambda: 'id(disp1).send_command_printf("vis dryActive,0");'
              - lambda: 'id(disp1).send_command_printf("vis fanActive,0");'
              - lambda: 'id(disp1).send_command_printf("vis %s,1", x.c_str());'
              - lambda: 'id(disp1).set_component_text_printf("targetTemp", "%i""\xb0", (int)id(target_temperature).state);'

# Define some outputs
switch:
  # The two relays
  - platform: gpio
    name: $device_name Relay 1
    id: relay_1
    pin:
      number: 22
    on_turn_on:
      - lambda: 'id(disp1).send_command_printf("leftButton.pic=19");'
    on_turn_off:
      - lambda: 'id(disp1).send_command_printf("leftButton.pic=21");'

  - platform: gpio
    name: $device_name Relay 2
    id: relay_2
    pin:
      number: 19
    on_turn_on:
      - lambda: 'id(disp1).send_command_printf("rightButton.pic=19");'
    on_turn_off:
      - lambda: 'id(disp1).send_command_printf("rightButton.pic=21");'

  # Pin 4 always needs to be on to power up the display
  - platform: gpio
    id: screen_power
    entity_category: config
    pin:
      number: 4
      inverted: true
    restore_mode: ALWAYS_ON

number:
  platform: template
  name: $device_name Brightness
  id: brightness
  entity_category: config
  unit_of_measurement: '%'
  min_value: 0
  max_value: 100
  step: 1
  initial_value: 30
  set_action:
    then:
      - lambda: 'id(disp1).set_backlight_brightness(x/100);'

# Configure the internal bleeper
output:
  - platform: ledc
    id: buzzer_out
    pin:
      number: 21

# Enable ringtone music support
rtttl:
  id: buzzer
  output: buzzer_out

# Configure UART for communicating with the screen
uart:
  id: tf_uart
  tx_pin: 16
  rx_pin: 17
  baud_rate: 115200

# Configure the screen itself
display:
  - platform: nextion
    id: disp1
    uart_id: tf_uart
    tft_url: http://192.168.1.150:8123/local/nspanel_demo.tft
    # A little fun...
    on_setup:
      then:
        - number.set:
            id: brightness
            value: 30
        - lambda: |-
            if (id(current_mode).state == "0") {
              id(disp1).set_component_text_printf("targetTemp", "--""\xb0");
              id(disp1).send_command_printf("vis heatActive,0");
              id(disp1).send_command_printf("vis coolActive,0");
              id(disp1).send_command_printf("vis dryActive,0");
              id(disp1).send_command_printf("vis fanActive,0");
            } else {
              id(disp1).set_component_text_printf("targetTemp", "%i""\xb0", (int)id(target_temperature).state);
              id(disp1).send_command_printf("vis heatActive,0");
              id(disp1).send_command_printf("vis coolActive,0");
              id(disp1).send_command_printf("vis dryActive,0");
              id(disp1).send_command_printf("vis fanActive,0");
              id(disp1).send_command_printf("vis %s,1", id(current_mode).state.c_str());
            }
            id(disp1).set_component_text_printf("currentTemp", "%i""\xb0", (int)id(current_temperature).state);
            if (id(relay_1).state == 1) {
              id(disp1).send_command_printf("leftButton.pic=19");
            } else {
              id(disp1).send_command_printf("leftButton.pic=21");
            }
            if (id(relay_2).state == 1) {
              id(disp1).send_command_printf("rightButton.pic=19");
            } else {
              id(disp1).send_command_printf("rightButton.pic=21");
            }
            
        # - rtttl.play: "twobits:d=4,o=5,b=220:c6,8g,8g,a,g,p,b,c6"